version: '3.5'

services:
  db_auth:
    container_name: db_auth
    ports:
      - ${db_port_auth}:${db_port_auth}
    environment: 
      POSTGRES_USER: ${db_user_auth}
      POSTGRES_PASSWORD: ${db_password_auth}
    image:  postgres:15-alpine 
    command:
      - 'postgres'
      - '-c'
      - 'port=${db_port_auth}'
    volumes:
      - db_auth_vol:/var/lib/postgres/data
    networks:
      - server_net

volumes:
  db_auth_vol: {}
networks:
  server_net:
    driver: bridge


