name: auth
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  grpc: ^3.2.0
  protobuf: ^3.0.0
  fixnum: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  protoc_plugin: ^21.0.0
  lints: ^2.1.1
